use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006009
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
Adam
Kennedy
adamk
Karen
Etheridge
ether
David
Golden
dagolden
Ingy
döt
Net
ingy
James
Keenan
jkeenan
Steffen
Müller
smueller
Alexandr
Ciornii
chorny
Graham
Knop
haarg
Hilko
Bengen
bengen
יובל
קוג
Yuval
Kogman
nothingmuch
Neil
Bowers
neil
Olivier
Mengué
dolmen
Slaven
Rezic
slaven
Tim
Bunce
Craig
Berry
craigberry
lib
YAML
Tiny
